spring.application.name=TgMail
# ===== Telegram =====
bot.token=${TG_BOT_TOKEN:8495548419:AAEei-QAXhRIwVu0OdLUiNNl-KLl3x1kt30}
bot.username=${TG_BOT_USERNAME:TG_MAIL_123bot}
bot.chat-id=-5435036346

# ===== IMAP / ????? =====
mail.imap.host=${IMAP_HOST:imap.mail.ru}
mail.imap.port=${IMAP_PORT:993}
mail.user=${MAIL_USER:Pro.masters@list.ru}
mail.password=${MAIL_PASSWORD:0RsxXWzD3rhPQVWhXYiY}

# ???????? ???????? ????? ? ????????
mail.poll-interval-seconds=${POLL_INTERVAL_SECS:60}